---
name: setup
description: Sets up the environment to run project's scripts.

inputs:
  python-version:
    description: The version of Python to use.
    required: false
    default: '3.11'

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true

    - name: Set up Python ${{ inputs.python-version }}
      run: |
        uv pip install --upgrade pip setuptools
      shell: bash

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      shell: bash
      run: uv pip install .[dev]
